---
title: "Boston Interactive Map"
author: "Nick Grammas"
date: 2020-12-01T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Interactive Property Map

```{r}
library(tidyverse)
library(usdata)
library(maps)
state_stats
state_df <- ggplot2::map_data("state")
mass <- state_df %>% filter(region == "massachusetts")
mass

library(devtools)
library(tidyverse)
library(uszipcodes)
library(maps)
library(leaflet)

## install.packages("devtools")
library(devtools)
#> Loading required package: usethis
## devtools::install_github("li-wen-li/uszipcodes")
library(uszipcodes)

properties <- read_csv("Data/zillow-boston.csv")
properties <- properties %>% filter(rstate == "MA")
raw_zip <- uszipcodes::get_zip(properties$address)
properties$Zip <- as.integer(uszipcodes::clean_zip(raw_zip))
#> Warning: NAs introduced by coercion

## only keep zip, lat, and long
zip_tab <- zip_table %>% dplyr::select(Zip, Latitude, Longitude)
property_location <- inner_join(properties, zip_tab)

uscities <- maps::us.cities

boston <- uscities %>% filter(name == "Boston MA")
view(boston)


content <- boston %>%
  mutate(popup = paste0(name))

properties$label <- paste("Address", properties$address, "<br/>",
                               "Price", properties$price, ",",
                               "Living Space", properties$living_space, ",",
                               "Property Type", properties$property_type, ",") %>%
  lapply(htmltools :: HTML)

boston_map <- leaflet(boston) %>%
  setView(lng = -71.02, lat = 42.34, zoom = 5) %>% 
  addTiles() %>% 
  addProviderTiles(providers$Wikimedia) %>% 
    addMarkers(lng = properties$longitude, lat = properties$latitude,
             clusterOptions = markerClusterOptions(),
             popup = content$popup,
             label = as.character(properties$label))

boston_map

```

  addMarkers(lng = properties$longitude, lat = properties$latitude,
            clusterOptions = markerClusterOptions()
             popup = content$popup,
             label = as.character(properties$label))